spring:
  profiles:
    active: mysql

#日志输出
logging:
  level:
    com.fx.server: debug

jwt:
  token-header: Authorization
  expire: 14400
  rsa-secret: xx1WET12^%3^(WE45

auth:
  user:
    token-header: Authorization